AluguelEquipamentos/Controllers/AluguelController.cs
using AluguelEquipamentos.Data;
using AluguelEquipamentos.Negocio.Interfaces;
using AluguelEquipamentos.Negocio.Models;
using Microsoft.AspNetCore.Mvc;

namespace AluguelEquipamentos.Controllers
{
    public class AluguelController : Controller
    {
        readonly private ApplicationDbContext _context;
        private readonly RabbitMQService _rabbitMQService;
        private readonly ISessao _sessao;

        public AluguelController(ApplicationDbContext dbContext,ISessao sessao, RabbitMQService rabbitMQService)
        {

            _context = dbContext;
            _rabbitMQService = rabbitMQService;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            var usuario = _sessao.BuscarSessao();
            
            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }
            IEnumerable<EquipamentoModel> equipamentos = _context.Equipamentos;
            return View(equipamentos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            var usuario = _sessao.BuscarSessao();

            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }

            return View();  
        }

        [HttpPost]
        public IActionResult Cadastrar(EquipamentoModel equipamento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipamento);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

                _rabbitMQService.SendMessage($"Novo aluguel cadastrado para o cliente {equipamento.Cliente}");

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            var usuario = _sessao.BuscarSessao();

            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }

            if (id == null || id == 0)
            {
                return NotFound();
            }

            EquipamentoModel aluguel = _context.Equipamentos.FirstOrDefault(x=>x.Id == id); 
            
            if (aluguel == null)
            {
                return NotFound();
            }


            return View(aluguel);
        }


        [HttpPost]
        public IActionResult Editar(EquipamentoModel equipamento)
        {
            if (ModelState.IsValid) 
            { 
              _context.Equipamentos.Update(equipamento);
              _context.SaveChanges();

                _rabbitMQService.SendMessage($"Alteração cadastro cliente {equipamento.Cliente}");

                TempData["MensagemSucesso"] = "Alteração realizada com sucesso!";
              return RedirectToAction("Index");
            }

            TempData["MensagemError"] = "Erro ao Relizar Edição Tente Novamente.";
            return View(equipamento);
        }

        [HttpGet]
        public IActionResult Excluir(int? id) 
        {
            var usuario = _sessao.BuscarSessao();

            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }

            if (id == null || id == 0)
            {
                return NotFound();
            }

            EquipamentoModel equipamentoModel = _context.Equipamentos.FirstOrDefault(x=>x.Id == id);

            if (equipamentoModel == null)
            {
                return NotFound();
            }

            return View(equipamentoModel);

        }

        [HttpPost]
        public IActionResult Excluir(EquipamentoModel equipamento)
        {
            if (equipamento == null) 
            {
                return NotFound();
            }

            _context.Remove(equipamento);
            _context.SaveChanges();

            _rabbitMQService.SendMessage($"Cadastro cliente Excluido {DateTime.Now} {equipamento.Cliente}");

            TempData["MensagemSucesso"] = "Exclusão realizada com sucesso!";

            return RedirectToAction("Index");

        }
    }
}

AluguelEquipamentos/Controllers/EnderecoController.cs
using AluguelEquipamentos.Data;
using AluguelEquipamentos.Negocio.Interfaces;
using AluguelEquipamentos.Negocio.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

public class EnderecoController : Controller
{
    private readonly IEnderecoService _enderecoService;
    readonly private ApplicationDbContext _context;
    readonly private ISessao _sessao;


    public EnderecoController(IEnderecoService enderecoService, ApplicationDbContext dbContext,ISessao sessao)
    {
        _context = dbContext;
        _enderecoService = enderecoService;
        _sessao = sessao;
    }

    public IActionResult Index()
    {
        var usuario = _sessao.BuscarSessao();

        if (usuario == null)
        {
            return RedirectToAction("Login", "Login");
        }
        IEnumerable<EnderecoModel> enderecos = _context.Endereco;
        return View(enderecos);
    }
    [HttpGet]
    public IActionResult Cadastrar()
    {
        var usuario = _sessao.BuscarSessao();

        if (usuario == null)
        {
            return RedirectToAction("Login", "Login");
        }
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(EnderecoModel endereco)
    {
        if (ModelState.IsValid)
        {
            _context.Add(endereco);
            _context.SaveChanges();

            TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

            return RedirectToAction("Index");
        }

        return View();
    }

    [HttpGet]
    public IActionResult Editar(int? id)
    {

        var usuario = _sessao.BuscarSessao();

        if (usuario == null)
        {
            return RedirectToAction("Login", "Login");
        }

        if (id == null || id == 0)
        {
            return NotFound();
        }

       EnderecoModel endereco = _context.Endereco.FirstOrDefault(x => x.IdEndereco == id);

        if (endereco == null)
        {
            return NotFound();
        }

        return View(endereco);
    }

    [HttpPost]
    public IActionResult Editar(EnderecoModel endereco)
    {
        if (ModelState.IsValid)
        {
            _context.Endereco.Update(endereco);
            _context.SaveChanges();

            TempData["MensagemSucesso"] = "Alteração realizada com sucesso!";
            return RedirectToAction("Index");
        }

        TempData["MensagemError"] = "Erro ao Relizar Edição Tente Novamente.";
        return View(endereco);
    }


    [HttpGet]
    public IActionResult Excluir(int? id)
    {
        var usuario = _sessao.BuscarSessao();

        if (usuario == null)
        {
            return RedirectToAction("Login", "Login");
        }

        if (id == null || id == 0)
        {
            return NotFound();
        }

        EnderecoModel endereco = _context.Endereco.FirstOrDefault(x => x.IdEndereco == id);

        if (endereco == null)
        {
            return NotFound();
        }

        return View(endereco);

    }

    [HttpPost]
    public IActionResult Excluir(EnderecoModel endereco)
    {
        if (endereco == null)
        {
            return NotFound();
        }

        _context.Remove(endereco);
        _context.SaveChanges();

        TempData["MensagemSucesso"] = "Exclusão realizada com sucesso!";

        return RedirectToAction("Index");

    }

    [HttpPost]
    public async Task<IActionResult> BuscarEndereco([FromBody] JsonElement jsonData)
    {
        var usuario = _sessao.BuscarSessao();

        if (usuario == null)
        {
            return RedirectToAction("Login", "Login");
        }
        if (!jsonData.TryGetProperty("cep", out JsonElement cepElement))
        {
            return BadRequest(new { mensagem = "CEP inválido." });
        }

        string cep = cepElement.GetString();

        if (string.IsNullOrWhiteSpace(cep) || cep.Length != 8)
        {
            return BadRequest(new { mensagem = "CEP inválido." });
        }

        var response = await _enderecoService.BuscarEndereco(cep);

        if (response?.DadosRetorno == null)
        {
            return NotFound(new { mensagem = "Endereço não encontrado." });
        }

        var endereco = new
        {
            cep = response.DadosRetorno.CEP,
            street = response.DadosRetorno.Street,
            neighborhood = response.DadosRetorno.Neighborhood,
            city = response.DadosRetorno.City,
            state = response.DadosRetorno.State
        };

        return Json(endereco);
    }

}

AluguelEquipamentos/Views/Endereco/Cadastrar.cshtml
@using AluguelEquipamentos.Negocio.Models
@model EnderecoModel

@{
    ViewData["title"] = "Cadastrar Endereco";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de Endereço</h1>

    </div>


    <form method="post" asp-controller="Endereco" asp-action="Cadastrar">

        <div class="mb-3">
            <label for="Cep" class="form-label text-light">CEP:</label>
            <input type="text" class="form-control" asp-for="cep" id="CEP" placeholder="Digite CEP">
            <span class="text-danger" asp-validation-for="cep"></span>
        </div>
        <div class="mb-3">
            <label for="Estado" class="form-label text-light">Estado:</label>
            <input type="text" class="form-control" asp-for="state" id="Estado" placeholder="Digite Estado">
            <span class="text-danger" asp-validation-for="state"></span>
        </div>
        <div class="mb-3">
            <label for="Cidade" class="form-label text-light">Cidade:</label>
            <input type="text" class="form-control" asp-for="city" id="Cidade" placeholder="Digite Cidade">
            <span class="text-danger" asp-validation-for="city"></span>
        </div>
        <div class="mb-3">
            <label for="Bairro" class="form-label text-light">Bairro:</label>
            <input type="text" class="form-control" asp-for="neighborhood" id="Bairro" placeholder="Digite Bairro">
            <span class="text-danger" asp-validation-for="neighborhood"></span>
        </div>
        <div class="mb-3">
            <label for="Rua" class="form-label text-light">Rua:</label>
            <input type="text" class="form-control" asp-for="street" id="Rua" placeholder="Digite Rua">
            <span class="text-danger" asp-validation-for="street"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">salvar</button>
            <a class=" btn btn-primary w-50" asp-controller="Aluguel" asp-action="Index">Voltar</a>
        </div>

    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("CEP").addEventListener("blur", async function () {
            let cep = this.value.replace(/\D/g, "");

            if (cep.length !== 8) {
                alert("CEP inválido.");
                return;
            }

            try {
                let response = await fetch("/Endereco/BuscarEndereco", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ cep: cep })
                });

                if (!response.ok) {
                    let errorData = await response.json();
                    alert(errorData.mensagem);
                    return;
                }

                let data = await response.json();
                document.getElementById("Estado").value = data.state || "";
                document.getElementById("Cidade").value = data.city || "";
                document.getElementById("Bairro").value = data.neighborhood || "";
                document.getElementById("Rua").value = data.street || "";

            } catch (error) {
                console.error("Erro ao buscar endereço:", error);
                alert("Erro ao buscar endereço.");
            }
        });
    });
</script>

AluguelEquipamentos/Views/Endereco/Editar.cshtml
@using AluguelEquipamentos.Negocio.Models
@model EnderecoModel
@{
    ViewData["title"] = "Editar Endereco";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Editar Endereço</h1>

    </div>

    <form method="post" asp-controller="Endereco" asp-action="Editar">

        <input type="hidden" asp-for="IdEndereco" />

        <div class="mb-3">
            <label for="Cep" class="form-label text-light">CEP:</label>
            <input type="text" class="form-control" asp-for="cep" id="CEP" placeholder="Digite CEP">
            <span class="text-danger" asp-validation-for="cep"></span>
        </div>
        <div class="mb-3">
            <label for="Estado" class="form-label text-light">Estado:</label>
            <input type="text" class="form-control" asp-for="state" id="Estado" placeholder="Digite Estado">
            <span class="text-danger" asp-validation-for="state"></span>
        </div>
        <div class="mb-3">
            <label for="Cidade" class="form-label text-light">Cidade:</label>
            <input type="text" class="form-control" asp-for="city" id="Cidade" placeholder="Digite Cidade">
            <span class="text-danger" asp-validation-for="city"></span>
        </div>
        <div class="mb-3">
            <label for="Bairro" class="form-label text-light">Bairro:</label>
            <input type="text" class="form-control" asp-for="neighborhood" id="Bairro" placeholder="Digite Bairro">
            <span class="text-danger" asp-validation-for="neighborhood"></span>
        </div>
        <div class="mb-3">
            <label for="Rua" class="form-label text-light">Rua:</label>
            <input type="text" class="form-control" asp-for="street" id="Rua" placeholder="Digite Rua">
            <span class="text-danger" asp-validation-for="street"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class=" btn btn-primary w-50" asp-controller="Endereco" asp-action="Index">Voltar</a>
        </div>

    </form>
</div>

AluguelEquipamentos/Views/Endereco/Excluir.cshtml
@using AluguelEquipamentos.Negocio.Models
@model EnderecoModel
@{
    ViewData["title"] = "Exluir Endereco";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir Cadastro Endereco</h1>
        
    </div>


    <form method="post" asp-controller="Endereco" asp-action="Excluir">

        <input type="hidden" asp-for="IdEndereco" />

        <div class="mb-3">
            <label for="Cep" class="form-label text-light">CEP:</label>
            <input type="text" class="form-control" asp-for="cep" id="CEP" placeholder="Digite CEP">
            <span class="text-danger" asp-validation-for="cep"></span>
        </div>
        <div class="mb-3">
            <label for="Estado" class="form-label text-light">Estado:</label>
            <input type="text" class="form-control" asp-for="state" id="Estado" placeholder="Digite Estado">
            <span class="text-danger" asp-validation-for="state"></span>
        </div>
        <div class="mb-3">
            <label for="Cidade" class="form-label text-light">Cidade:</label>
            <input type="text" class="form-control" asp-for="city" id="Cidade" placeholder="Digite Cidade">
            <span class="text-danger" asp-validation-for="city"></span>
        </div>
        <div class="mb-3">
            <label for="Bairro" class="form-label text-light">Bairro:</label>
            <input type="text" class="form-control" asp-for="neighborhood" id="Bairro" placeholder="Digite Bairro">
            <span class="text-danger" asp-validation-for="neighborhood"></span>
        </div>
        <div class="mb-3">
            <label for="Rua" class="form-label text-light">Rua:</label>
            <input type="text" class="form-control" asp-for="street" id="Rua" placeholder="Digite Rua">
            <span class="text-danger" asp-validation-for="street"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class=" btn btn-primary w-50" asp-controller="Endereco" asp-action="Index">Voltar</a>
        </div>

    </form>
</div>

AluguelEquipamentos/Views/Endereco/Index.cshtml
@using AluguelEquipamentos.Negocio.Models
@model IEnumerable<EnderecoModel>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Cadastro Endereço</h1>
        <a class="btn btn-success ms-2" asp-controller="Endereco" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus-fill mx-2"></i>Cadastrar endereço Equipamento</a>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-dark" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemError"] != null)
    {
        <div class="alert alert-danger text-dark" role="alert">
            @TempData["MensagemError"]
        </div>
    }

    <table id="Endereco" class="table table-light table-hover mt-3">
        <thead>
            <tr>
                <th scope="col">CEP</th>
                <th scope="col">Rua</th>
                <th scope="col">Bairro</th>
                <th scope="col">Cidade</th>
                <th scope="col">Estado</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var endereco in Model)
                {
                    <tr>
                        <td>@endereco.cep</td>
                        <td>@endereco.street</td>
                        <td>@endereco.neighborhood</td>
                        <td>@endereco.city</td>
                        <td>@endereco.state</td>
                        <td>
                            <a asp-controller="Endereco" asp-action="editar" asp-route-id="@endereco.IdEndereco" class="btn btn-warning me-2"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            <a asp-controller="Endereco" asp-action="excluir" asp-route-id="@endereco.IdEndereco" class="btn btn-danger"><i class="bi bi-trash3-fill mx-2"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>